# Generated by Django 5.2.2 on 2025-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationqualification',
            name='education_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='education_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='education_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='graduation_year_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='graduation_year_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
