# Generated by Django 5.2.2 on 2025-06-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_title', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.CharField(blank=True, max_length=100)),
                ('permanent_address', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('gender', models.CharField(choices=[('no', 'Select'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='no', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
