# Generated by Django 5.2.2 on 2025-06-29 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_company_address_account_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_degree', models.CharField(max_length=100)),
                ('education_board', models.CharField(max_length=100)),
                ('education_institution', models.CharField(max_length=100)),
                ('graduation_year_from', models.DateField()),
                ('graduation_year_to', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
