# Generated by Django 5.2.2 on 2025-06-30 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('jobType', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_slug', models.SlugField(max_length=100, unique=True)),
                ('application_deadline', models.DateField(null=True)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('job_post_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobType.jobtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
